<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 *
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateUnitUnitRequestTable extends Migration
{

    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('units', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name', 255);
            $table->longText('description');
            $table->text('height');
            $table->text('width');
            $table->text('price');
            $table->nullableTimestamps();
            $table->integer('product_id')->nullable();
            $table->text('weight')->nullable();
            $table->text('length')->nullable();
            $table->text('model')->nullable();
            $table->softDeletes();
        });
        Schema::create('unit_unit_request', function (Blueprint $table) {
            $table->unsignedInteger('unit_id');
            $table->unsignedInteger('unit_request_id');

            $table->primary(['unit_id', 'unit_request_id']);
            $table->index('unit_id', 'units_unit_requests_unit_id_index');
            $table->index('unit_request_id', 'units_unit_requests_unit_request_id_index');

            $table->foreign('unit_id', 'units_unit_requests_unit_id_foreign')->references('id')->on('units')->onDelete('CASCADE
')->onUpdate('RESTRICT');
            $table->foreign('unit_request_id', 'units_unit_requests_unit_request_id_foreign')->references('id')->on('unit_requests')->onDelete('CASCADE
')->onUpdate('RESTRICT');

        });
    }


    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('units');
        Schema::dropIfExists('unit_unit_request');
    }
}
