<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateCategoriesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('categories', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('parent_id')->nullable();
            $table->integer('lft')->nullable();
            $table->integer('rgt')->nullable();
            $table->integer('depth')->nullable();
            $table->string('name', 255);
            $table->string('slug', 255);
            $table->integer('position')->nullable();
            $table->longText('intro_text');
            $table->nullableTimestamps();
            $table->integer('enabled')->nullable();
            $table->text('title')->nullable();
            $table->text('meta_description');
            $table->softDeletes();

            $table->unique('slug', 'categories_slug_unique');
            $table->index('parent_id', 'categories_parent_id_index');
            $table->index('lft', 'categories_lft_index');
            $table->index('rgt', 'categories_rgt_index');

            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('categories');
    }
}
